# Generated by Django 3.1.4 on 2020-12-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=255)),
                ('servico_interessado', models.CharField(choices=[('LF', 'Lógica Flow'), ('LA', 'Lógica For Assinantes'), ('LE', 'Lógica ERP'), ('LT', 'Lógica for Técnicos'), ('LP', 'Lógica Fone'), ('LC', 'Lógica Active')], default='LE', max_length=2)),
            ],
        ),
    ]
